### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by hxngiee** [genforce/eqgan#1]
Thank you so much for this amazing work

I wonder if you have any plans to release code for training

**Comment by jytime** [comment]
Hi,

This work has been accepted. We are going to release the code soon.

Best,
Jianyuan

**Comment by jytime** [comment]
Hi @hxngiee, 

Thanks for your interest in our work. The code and pre-trained model have been released. Please let me know if you have any questions.

**Comment by hxngiee** [comment]
> Hi @hxngiee,
> 
> Thanks for your interest in our work. The code and pre-trained model have been released. Please let me know if you have any questions.

Hi, @jytime,

Thanks you so much for letting me know!

I look forward to your future research

good luck!
