### ISSUE TITLE
How to generate images with pretrained network?

### ISSUE THREAD

**Issue by StevenShaw1999** [genforce/eqgan#3]
Hello! Thank you for open source your code.
I wonder how to generate images with the provided models (e.g. LSUN cat).
I found that the 'generate.py' only supports image generation with the online pretrained models (e.g. https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metfaces.pkl)
Looking forward to your reply.

**Comment by jytime** [comment]
Hi,

You can generate images by feeding a model's path to --network of generate.py.
For example, download LSUN Cat model to your local machine as /home/someone/cat.pkl, and then 

`python generate.py --outdir=out --trunc=1 --seeds=85,265,297,849 --network=/home/someone/cat.pkl
`

**Comment by jytime** [comment]
I have updated the information in section [Evaluation](https://github.com/genforce/eqgan-sa#evaluation). Please let me know if you have any other questions.

**Comment by StevenShaw1999** [comment]
This helps for me! Thank you for your quick and helpful reply~
