### ISSUE TITLE
For performance reproduction 

### ISSUE THREAD

**Issue by Sang-Yeop-Yeo** [genforce/eqgan#5]
Hi Thank you for sharing the code.

I'm simply reworking your code for FFHQ datasets as below.

"python train.py --outdir=~ --data=~/ffhq256x256.zip --gpus=8 --cfg=paper256 --aug=noaug --pl_w=0 --close_style_mixing=True --use_sel=True --align_loss=True"

"python train.py --outdir=~ --data=~/ffhq256x256.zip --gpus=8 --cfg=paper256 --aug=noaug --pl_w=0 --close_style_mixing=True --use_sel=False --align_loss=False"

However, contrary to the results of the paper, DI is better when SEL and align_loss are not used.

The only code I changed was to change the two lines below because of the error that came out when using use_sel and algin_loss as false.

"                    alignment_loss = align_loss_sum
                else:
                    alignment_loss = 0.0
"

"
module = torch.nn.parallel.DistributedDataParallel(module, device_ids=[device], broadcast_buffers=False, find_unused_parameters=True)
"

Is there any problem with me?

**Comment by Sang-Yeop-Yeo** [comment]
I observed that the teaser image of the paper was experimented for LSUN_CAT datasets.

So, I also experimented for LSUN.

Then, I could see a similar trend to the paper.

But I still can't see the trend for FFHQ datasets, was it the same when you experimented?

**Comment by jytime** [comment]
Hi,

The trend should be the same for these datasets. It sounds a bit weird. May I ask what's the performance of other metrics in your running? 

And, I was not sure if " module = torch.nn.parallel.DistributedDataParallel(module, device_ids=[device], broadcast_buffers=False, find_unused_parameters=True) " should be changed.  Could I ask what's the error raised by this line? One thing I can think of is possibly setting find_unused_parameters=False, which means there are parameters defined in the graph but not involved in training/evaluation.
